<?php

// autoload_classmap.php @generated by TYPO3

$typo3InstallDir = PATH_site;

return array(
    'ArminVieweg\\Dce\\' => array($typo3InstallDir . 'typo3conf/ext/dce/Classes'),
    'ArminVieweg\\T3ddy\\' => array($typo3InstallDir . 'typo3conf/ext/t3ddy/Classes'),
    'GeorgRinger\\Eventnews\\' => array($typo3InstallDir . 'typo3conf/ext/eventnews/Classes'),
    'GeorgRinger\\News\\' => array($typo3InstallDir . 'typo3conf/ext/news/Classes'),
    'GridElementsTeam\\Gridelements\\' => array($typo3InstallDir . 'typo3conf/ext/gridelements/Classes'),
    'Hoogi91\\Spreadsheets\\' => array($typo3InstallDir . 'typo3conf/ext/spreadsheets/Classes'),
    'Keizer\\KoningBootstrapCarousel\\' => array($typo3InstallDir . 'typo3conf/ext/koning_bootstrap_carousel/Classes'),
    'SGalinski\\dfContentslide\\' => array($typo3InstallDir . 'typo3conf/ext/df_contentslide/Classes'),
    'TeaminmediasPluswerk\\KeSearch\\' => array($typo3InstallDir . 'typo3conf/ext/ke_search/Classes'),
    'YolfTypo3\\SavCharts\\' => array($typo3InstallDir . 'typo3conf/ext/sav_charts/Classes'),
);
